### ISSUE TITLE
Upstream the repo

### ISSUE THREAD

**Issue by bprashanth** [mingfang/docker-knginx#1]
I noticed this on the google-containers mailing list and decided to reach out. It would be great if you could upstream this repo into [Ingress/controllers](https://github.com/kubernetes/contrib/tree/master/Ingress/controllers). I'm willing to help clarify/take patches to support things that might not work right away. I think it will be worth your time because we're currently fleshing out the L7 api for Ingress, your feedback will be pretty valuable. We already have a [haproxy controller](https://github.com/kubernetes/contrib/tree/master/service-loadbalancer) that we'll be moving into Ingress very soon. 

You will however, need to watch the kubernetes apiserver Ingress resource. confd->etcd bridge will work in simpler cases but gets really difficult to manage real/multiple frontends etc. If you're interested in writing go code, I can tell you how. This is just my 2c.

**Comment by mingfang** [comment]
@bprashanth 
Thanks for heads up.
I will track the Ingress progress and see if it makes sense to use it later.
